name: Development Build For Pull Requests
on:
  pull_request:
    types: [opened]
    branches:
      - development
env:
  MY_GITHUB_TOKEN: ${{ secrets.AUTOMATE_ISSUES }}
jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to MVP Frontend Project
    steps:
    - name: Assign NEW pull-request to MVP Backend Project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/My-Power-STN39M-Hopefully/projects/1'
  build:
    runs-on: ubuntu-latest
    name: Build Pull Request
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v1
    - name: Build Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Install
      run: |
        yarn install
    - name: Development Build
      run: |
        yarn build
      env:
        CI: ""
