name: Build For Pull Requests
on:
  pull_request:
    types: [opened, synchronize]
env:
  MY_GITHUB_TOKEN: ${{ secrets.AUTOMATE_ISSUES_PULL_REQUESTS }}
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Pull Request
    strategy:
      matrix:
        node-version: [12.x]     
    steps:
    - uses: actions/checkout@v1
    - name: Build Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Install
      run: |
        yarn install
    - name: Build PR
      run: |
        yarn build
      env:
        CI: ""
